version: 2.1

executors:
  docker:
    working_directory: ~/workspace
    docker:
      - image: docker:18.03-git

commands:
  docker_build:
    description: Push image to registory
    parameters:
      repository:
        type: string
    steps:
      - run:
          command: docker build -t << parameters.repository >> .
  docker_push:
    description: Push image to registory
    parameters:
      repository:
        type: string
    steps:
      - run:
          command: |
            export TAG=`date +%Y.%m.%d`
            docker tag << parameters.repository >> << parameters.repository >>:${TAG}
            docker push << parameters.repository >>:${TAG}

jobs:
  build_and_push:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push docker image
          command: |
            git fetch origin master
            git diff
            git merge-base origin/master HEAD


workflows:
  build:
    jobs:
      - build_and_push:
          filters:
            branches:
              ignore: []
